"""Configuration management for Arodonata library."""

from .constants import (
    DEFAULT_API_TIMEOUT,
    DEFAULT_CONCURRENT_LIMIT,
    DEFAULT_LOGIN_BACKOFF,
    DEFAULT_LOGIN_RETRIES,
    DEFAULT_SESSION_EXPIRE,
    DEFAULT_SESSION_TIMEOUT,
    FAILOVER_ERROR_CODES,
    LOG_LEVELS,
    SESSION_ERROR_CODES,
    THROTTLE_ERROR_CODE,
)
from .settings import ArodonataSettings

__all__ = [
    "ArodonataSettings",
    "DEFAULT_SESSION_EXPIRE",
    "DEFAULT_SESSION_TIMEOUT",
    "DEFAULT_API_TIMEOUT",
    "DEFAULT_CONCURRENT_LIMIT",
    "DEFAULT_LOGIN_BACKOFF",
    "DEFAULT_LOGIN_RETRIES",
    "SESSION_ERROR_CODES",
    "THROTTLE_ERROR_CODE",
    "LOG_LEVELS",
    "FAILOVER_ERROR_CODES",
]
