"""Configuration management for Arodonata library."""

from .constants import (
    CREDENTIAL_REJECTION_MESSAGE,
    DEFAULT_API_TIMEOUT,
    DEFAULT_CONCURRENT_LIMIT,
    DEFAULT_LOGIN_BACKOFF,
    DEFAULT_LOGIN_MAX_WAIT,
    DEFAULT_LOGIN_RETRIES,
    DEFAULT_LOGIN_TIMEOUT,
    DEFAULT_SESSION_EXPIRE,
    DEFAULT_SESSION_TIMEOUT,
    FAILOVER_ERROR_CODES,
    GLOBAL_DOMAIN_NAME,
    LOG_LEVELS,
    LOGIN_THROTTLE_WINDOW_SECONDS,
    SERVER_UNREACHABLE_MESSAGE,
    SESSION_ERROR_CODES,
    THROTTLE_ERROR_CODE,
)
from .settings import ArodonataSettings

__all__ = [
    "ArodonataSettings",
    "DEFAULT_SESSION_EXPIRE",
    "DEFAULT_SESSION_TIMEOUT",
    "DEFAULT_API_TIMEOUT",
    "DEFAULT_CONCURRENT_LIMIT",
    "DEFAULT_LOGIN_BACKOFF",
    "DEFAULT_LOGIN_MAX_WAIT",
    "DEFAULT_LOGIN_RETRIES",
    "DEFAULT_LOGIN_TIMEOUT",
    "LOGIN_THROTTLE_WINDOW_SECONDS",
    "SESSION_ERROR_CODES",
    "THROTTLE_ERROR_CODE",
    "CREDENTIAL_REJECTION_MESSAGE",
    "SERVER_UNREACHABLE_MESSAGE",
    "LOG_LEVELS",
    "FAILOVER_ERROR_CODES",
    "GLOBAL_DOMAIN_NAME",
]
